openapi: 3.0.3
info:
  title: Computer Parts E-Shop API
  version: 1.0.0
  description: REST API for managing computer parts, including live WebSocket updates.

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /:
    get:
      summary: Welcome message
      description: Returns a welcome message for the API.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: "Welcome computer parts e-shop!"

  /parts:
    get:
      summary: Get all parts
      description: Returns all computer parts in the store.
      responses:
        '200':
          description: List of all parts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllParts'

  /parts/rams:
    get:
      summary: Get all RAM modules
      responses:
        '200':
          description: List of RAM components
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartsCategory'
        '400':
          description: Error or invalid request

  /parts/cpus:
    get:
      summary: Get all CPUs
      responses:
        '200':
          description: List of CPU components
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartsCategory'
        '400':
          description: Error or invalid request

  /parts/gpus:
    get:
      summary: Get all GPUs
      responses:
        '200':
          description: List of GPU components
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartsCategory'
        '400':
          description: Error or invalid request

  /parts/disks:
    get:
      summary: Get all disks
      responses:
        '200':
          description: List of disk components
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartsCategory'
        '400':
          description: Error or invalid request

  /parts/motherboards:
    get:
      summary: Get all motherboards
      responses:
        '200':
          description: List of motherboard components
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartsCategory'
        '400':
          description: Error or invalid request

  /parts/power_supplies:
    get:
      summary: Get all power supplies
      responses:
        '200':
          description: List of power supply components
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartsCategory'
        '400':
          description: Error or invalid request

  /parts/rams/{id}:
    get:
      summary: Get RAM by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: RAM details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
        '400':
          description: RAM not found

  /parts/cpus/{id}:
    get:
      summary: Get CPU by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: CPU details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
        '400':
          description: CPU not found

  /parts/gpus/{id}:
    get:
      summary: Get GPU by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: GPU details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
        '400':
          description: GPU not found

  /parts/disks/{id}:
    get:
      summary: Get disk by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Disk details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
        '400':
          description: Disk not found

  /parts/motherboards/{id}:
    get:
      summary: Get motherboard by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Motherboard details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
        '400':
          description: Motherboard not found

  /parts/power_supplies/{id}:
    get:
      summary: Get power supply by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Power supply details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
        '400':
          description: Power supply not found

  /parts/order:
    put:
      summary: Place a pre-order
      description: Save a pre-order of components. Does not affect stock.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '200':
          description: Pre-order saved successfully
        '400':
          description: Invalid part type or ID

  /parts/buy:
    put:
      summary: Buy components
      description: Purchase components and reduce stock accordingly.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '200':
          description: Purchase successful
        '409':
          description: Some components unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuyConflictResponse'
        '400':
          description: Invalid part type or ID

components:
  schemas:
    Part:
      type: object
      properties:
        name:
          type: string
          example: "Kingston Fury 16GB"
        price:
          type: number
          example: 1299
        quantity:
          type: integer
          example: 5
        description:
          type: string
          example: "DDR4 3200MHz RAM"

    PartsCategory:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Part'

    AllParts:
      type: object
      properties:
        rams:
          $ref: '#/components/schemas/PartsCategory'
        cpus:
          $ref: '#/components/schemas/PartsCategory'
        gpus:
          $ref: '#/components/schemas/PartsCategory'
        disks:
          $ref: '#/components/schemas/PartsCategory'
        motherboards:
          $ref: '#/components/schemas/PartsCategory'
        power_supplies:
          $ref: '#/components/schemas/PartsCategory'

    OrderRequest:
      type: object
      description: Mapping of component type to component ID
      additionalProperties:
        type: string
      example:
        ram: "id1"
        cpu: "id1"
        gpu: "id2"

    BuyConflictResponse:
      type: object
      properties:
        unavailableParts:
          type: object
          additionalProperties:
            type: string
        availableParts:
          type: object
          additionalProperties:
            type: string
